blank_issues_enabled: false

contact_links:
  - name: Support Disclaimer
    url: https://github.com/Celarye/paperback-themes#support-disclaimer
    about: Please read this before creating any issue.
  - name: GitHub Issues
    url: https://github.com/Celarye/paperback-themes/issues
    about: Check to make sure there is not an issues already open that is related to your issue.
  - name: The Official Paperback Discord
    url: https://discord.com/invite/Paperback
    about: "For quick Paperback app related support from the community (use the #support channel)."
