name: Theme Request
description: If you have a request for a theme.
title: '[REQUEST] '
labels: ['enhancement', 'theme']
assignees: ['Celarye']
body:
  - type: markdown
    id: message
    attributes:
      value: |
        Thanks for taking the time to fill out this theme request!
  - type: checkboxes
    id: preflight-checklist
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I have read and I agree to follow the [support disclaimer](https://github.com/Celarye/paperback-themes#support-disclaimer).
          required: true
        - label: I have checked if the theme isn't available already.
          required: true
        - label: I am requesting this theme for the latest available Paperback version (currently 0.8).
          required: true
        - label: I have searched the [issue tracker](https://github.com/Celarye/paperback-themes/issues) for a theme request that matches the one I want to file, without success.
          required: true
  - type: textarea
    id: theme-description
    attributes:
      label: Describe the theme
      description: A clear and concise description of the theme you would like to see added.
      placeholder: Tell us what you want!
    validations:
      required: true
  - type: textarea
    id: theme-motivation
    attributes:
      label: Theme Motivation
      description: Explain how the theme will improve the app.
      placeholder: Tell us the about the benefits!
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Anything Else?
      description: |
        Links? References? Anything that will give us more context about the theme which you are requesting!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: Images, links, ...
    validations:
      required: false
