name: Theme Creator Program Bug Report
description: If you encounter a bug with the Theme Creator program. Please use this template to help improve the Theme Creator program.
title: '[THEME CREATOR BUG] '
labels: ['bug', 'theme creator']
assignees: ['Celarye']
body:
  - type: markdown
    id: message
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: preflight-checklist
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I have read and I agree to follow the [support disclaimer](https://github.com/Celarye/paperback-themes#support-disclaimer).
          required: true
        - label: I am sure that I'm using the latest version of the Theme Creator program.
          required: true
        - label: I have read the [troubleshooting FAQs](https://github.com/Celarye/paperback-themes#faq), but it didn't solve my issue.
          required: true
        - label: I have searched the [issue tracker](https://github.com/Celarye/paperback-themes/issues) for a bug report that matches the one I want to file, without success.
          required: true
  - type: input
    id: os-version
    attributes:
      label: Operating System Version
      description: What operating system (and version) are you using?
      placeholder: "e.g. Windows 11 version 23H2, Linux Mint 21.3 Virginia or macOS Ventura 13.5"
    validations:
      required: true
  - type: dropdown
    id: computer-processor-architecture
    attributes:
      label: Computer Processor Architecture
      description: "What processor architecture does your computer have? Note: At this moment only x64 and ARM64 is supported[*](https://github.com/Celarye/paperback-themes#faq)."
      multiple: true
      options:
        - x64
        - ARM64
        - Other
    validations:
      required: true
  - type: input
    id: theme-creator-version
    attributes:
      label: Theme Creator Version
      description: What version of the Theme Creator program are you using?
      placeholder: "e.g. v1.0.0"
    validations:
      required: true
  - type: input
    id: paperback-app-version
    attributes:
      label: Paperback App Version
      description: What version of Paperback are you making the theme for? You can find this info at the bottom of the settings page from within the app.
      placeholder: "e.g. 0.8.6-r2"
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the bug that you encountered. Tell us what you expected to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: bug-replication
    attributes:
      label: Steps to Reproduce
      description: How did you produce this bug, tell us how you did it so we can reproduce it ourselves.
      placeholder: 1. ...
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: Anything Else
      description: |
        Anything that will give more context about the bug which you are encountering is also welcome!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: Images, links, logs, ...
    validations:
      required: false
